### ISSUE TITLE
Dragon Harpoon

### ISSUE THREAD

**Issue by Intecpsp** [JonneSaloranta/skilling-boost-reminder#1]
I'm not being reminded when using the Dragon Harpoon. Is that a covered item?

**Comment by Intecpsp** [comment]
I am still not seeing anything reminding me to spec after [this](https://github.com/runelite/plugin-hub/pull/6804) update

**Comment by JonneSaloranta** [comment]
Can you provide more information about which specific notification you are not seeing? Which item were you holding and which activity.

If you are not seeing the notification arrow, try changing the arrow Y offset setting.

If you are not getting tray,screenflash etc notification, check your runelite settings

and the chat notification should appear in chat.

Tested this fix and it was working correctly.

Also try resetting all your settings for this plugin.

**Comment by Intecpsp** [comment]
Does [this](https://imgur.com/a/kIVcQhN) help? I'm not seeing anything currently.

I get other RuneLite notifications, so I know those work. I also tried resetting the plugin settings.

**Comment by JonneSaloranta** [comment]
This helps! The fix was an actual issue with checking for wrong animation with dragon harpoon. 

Your issue is one of those edge cases that I worked on today(boosting with an item but not actually using it in the activity)

The current version in plugin hub only supports activities with the spec item(e.g dragon axe woodcutting, mining with dragon pick etc)

I'll probably push the update during the weekend.

**Comment by Intecpsp** [comment]
> Your issue is one of those edge cases that I worked on today(boosting with an item but not actually using it in the activity)
> 
> The current version in plugin hub only supports activities with the spec item(e.g dragon axe woodcutting, mining with dragon pick etc)

Will this fix using an item from the inventory (not equipped) as well? Example: Farming guild in farming outfit with Dragon Axe in inventory for chopping trees down does not currently trigger the notification as well.

**Comment by JonneSaloranta** [comment]
This is intentional behaviour. Currently, I don't plan on adding functionality for notifications when the item is only in the inventory because you can't use the special attack to boost unless, for example, the Dragon Axe is equipped. Once the item is equipped, the notification will trigger as expected. Not boosting while doing tree runs likely won't affect your efficiency significantly.

However, if there's an item that allows boosting without being equipped, I will likely add support for it specifically.

If things change, or if there is significant demand for this feature, I'll reconsider and take a look at it.

**Comment by Intecpsp** [comment]
> This is intentional behaviour. 

Understandable. What about a config value defaulted to false that would allow items in the inventory?

**Comment by JonneSaloranta** [comment]
That could be a good compromise although it won't be the first priority at the moment. I'll add it once all the base functionality is implemented.

I'll add it eventually but if you are interested and possess the know-how, feel free to leave a PR.
